## Creating Logistic Regressions to Predict Absenteeism

### Importing relevant libraries

In [1]:
import numpy as np
import pandas as pd
import warnings 
warnings.filterwarnings('ignore')

In [2]:
df= pd.read_csv("Absenteeism_preprocessed.csv")
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month  Day of the Week  \
0         0         0         0         1      7                1   
1         0         0         0         0      7                1   
2         0         0         0         1      7                2   
3         1         0         0         0      7                3   
4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

### Creating targets

In [3]:
df['Absenteeism Time in Hours'].median()

3.0

In [4]:
targets = np.where(df['Absenteeism Time in Hours']>df['Absenteeism Time in Hours'].median(), 1, 0)

In [5]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
df['Excessive Absenteeism'] = targets
df.head(2)

Reason_1  Reason_2  Reason_3  Reason_4  Month  Day of the Week  \
0         0         0         0         1      7                1   
1         0         0         0         0      7                1   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   

   Excessive Absenteeism  
0                      1  
1                      0

In [7]:
#Check Balance of targets
targets.sum()/targets.shape[0]

0.45571428571428574

In [8]:
data_with_targets= df.drop(['Absenteeism Time in Hours','Day of the Week',
                                            'Daily Work Load Average','Distance to Work'], axis=1)
data_with_targets.head(2)

Reason_1  Reason_2  Reason_3  Reason_4  Month  Transportation Expense  Age  \
0         0         0         0         1      7                     289   33   
1         0         0         0         0      7                     118   50   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0

In [9]:
data_with_targets.shape

(700, 12)

### Selecting inputs for model

In [10]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

### Standardize the data

In [11]:
from sklearn.preprocessing import StandardScaler

scaler= StandardScaler()

In [12]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [13]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [14]:
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [15]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [16]:
scaler = CustomScaler(columns_to_scale)

In [17]:
scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [18]:
scaled_inputs = scaler.transform(unscaled_inputs)

In [19]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4     Month  Transportation Expense  \
0           0         0         0         1  0.182726                1.005844   
1           0         0         0         0  0.182726               -1.574681   
2           0         0         0         1  0.182726               -0.654143   
3           1         0         0         0  0.182726                0.854936   
4           0         0         0         1  0.182726                1.005844   
..        ...       ...       ...       ...       ...                     ...   
695         1         0         0         0 -0.388293               -0.654143   
696         1         0         0         0 -0.388293                0.040034   
697         1         0         0         0 -0.388293                1.624567   
698         0         0         0         1 -0.388293                0.190942   
699         0         0         0         1 -0.388293                1.036026   

          Age  Body Mass Index  Education  Children      Pets  
0   -0.536062         0.767431          0  0.880469  0.268487  
1    2.130803         1.002633          0 -0.019280 -0.589690  
2    0.248310         1.002633          0 -0.919030 -0.589690  
3    0.405184        -0.643782          0  0.880469 -0.589690  
4   -0.536062         0.767431          0  0.880469  0.268487  
..        ...              ...        ...       ...       ...  
695  0.562059        -1.114186          1  0.880469 -0.589690  
696 -1.320435        -0.643782          0 -0.019280  1.126663  
697 -1.320435        -0.408580          1 -0.919030 -0.589690  
698 -0.692937        -0.408580          1 -0.919030 -0.589690  
699  0.562059        -0.408580          0 -0.019280  0.268487  

[700 rows x 11 columns]

In [20]:
scaled_inputs.shape

(700, 11)

### Splitting the Data

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, random_state=20)

In [22]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(560, 11) (560,)
(140, 11) (140,)


### Logistic Regression with sklearn

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [24]:
#Training the model

reg= LogisticRegression()

In [25]:
reg.fit(X_train, y_train)

LogisticRegression()

In [26]:
reg.score(X_train, y_train)

0.7732142857142857

In [27]:
reg.intercept_

array([-1.6474549])

In [28]:
reg.coef_

array([[ 2.80019733,  0.95188356,  3.11555338,  0.83900082,  0.1589299 ,
         0.60528415, -0.16989096,  0.27981088, -0.21053312,  0.34826214,
        -0.27739602]])

In [29]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [30]:
feature_name = unscaled_inputs.columns.values

In [31]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)
summary_table['Coefficients'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficients
0                 Reason_1      2.800197
1                 Reason_2      0.951884
2                 Reason_3      3.115553
3                 Reason_4      0.839001
4                    Month      0.158930
5   Transportation Expense      0.605284
6                      Age     -0.169891
7          Body Mass Index      0.279811
8                Education     -0.210533
9                 Children      0.348262
10                    Pets     -0.277396

In [32]:
summary_table.index= summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table= summary_table.sort_index()
summary_table

Feature name  Coefficients
0                Intercept     -1.647455
1                 Reason_1      2.800197
2                 Reason_2      0.951884
3                 Reason_3      3.115553
4                 Reason_4      0.839001
5                    Month      0.158930
6   Transportation Expense      0.605284
7                      Age     -0.169891
8          Body Mass Index      0.279811
9                Education     -0.210533
10                Children      0.348262
11                    Pets     -0.277396

In [33]:
summary_table['Odd_ratio'] = np.exp(summary_table.Coefficients)
summary_table.sort_values('Odd_ratio', ascending= False)

Feature name  Coefficients  Odd_ratio
3                 Reason_3      3.115553  22.545903
1                 Reason_1      2.800197  16.447892
2                 Reason_2      0.951884   2.590585
4                 Reason_4      0.839001   2.314054
6   Transportation Expense      0.605284   1.831773
10                Children      0.348262   1.416604
8          Body Mass Index      0.279811   1.322880
5                    Month      0.158930   1.172256
7                      Age     -0.169891   0.843757
9                Education     -0.210533   0.810152
11                    Pets     -0.277396   0.757754
0                Intercept     -1.647455   0.192539

### Testing the model

In [34]:
reg.score(X_test, y_test)

0.75

In [35]:
pred= reg.predict_proba(X_test)
pred

array([[0.71340413, 0.28659587],
       [0.58724228, 0.41275772],
       [0.44020821, 0.55979179],
       [0.78159464, 0.21840536],
       [0.08410854, 0.91589146],
       [0.33487603, 0.66512397],
       [0.29984576, 0.70015424],
       [0.13103971, 0.86896029],
       [0.78625404, 0.21374596],
       [0.74903632, 0.25096368],
       [0.49397598, 0.50602402],
       [0.22484913, 0.77515087],
       [0.07129151, 0.92870849],
       [0.73178133, 0.26821867],
       [0.30934135, 0.69065865],
       [0.5471671 , 0.4528329 ],
       [0.55052275, 0.44947725],
       [0.5392707 , 0.4607293 ],
       [0.40201117, 0.59798883],
       [0.05361575, 0.94638425],
       [0.7003009 , 0.2996991 ],
       [0.78159464, 0.21840536],
       [0.42037128, 0.57962872],
       [0.42037128, 0.57962872],
       [0.24783565, 0.75216435],
       [0.74566259, 0.25433741],
       [0.51017274, 0.48982726],
       [0.85690195, 0.14309805],
       [0.20349733, 0.79650267],
       [0.78159464, 0.21840536],
       [0.

In [36]:
pred.shape

(140, 2)

In [37]:
pred[:,1]

array([0.28659587, 0.41275772, 0.55979179, 0.21840536, 0.91589146,
       0.66512397, 0.70015424, 0.86896029, 0.21374596, 0.25096368,
       0.50602402, 0.77515087, 0.92870849, 0.26821867, 0.69065865,
       0.4528329 , 0.44947725, 0.4607293 , 0.59798883, 0.94638425,
       0.2996991 , 0.21840536, 0.57962872, 0.57962872, 0.75216435,
       0.25433741, 0.48982726, 0.14309805, 0.79650267, 0.21840536,
       0.36956558, 0.67906035, 0.68502567, 0.52868083, 0.21840536,
       0.53506551, 0.22147081, 0.73692105, 0.40498044, 0.60505988,
       0.21075848, 0.45224466, 0.23751292, 0.39833498, 0.82755447,
       0.56797575, 0.69113325, 0.28659587, 0.21935267, 0.2033097 ,
       0.57628256, 0.3294664 , 0.66512397, 0.26949499, 0.83321968,
       0.43491525, 0.88374612, 0.23127072, 0.33415858, 0.34432939,
       0.69909345, 0.65494263, 0.29244941, 0.79200758, 0.20750276,
       0.26840558, 0.08708566, 0.22147081, 0.73245417, 0.30530219,
       0.22147081, 0.29014408, 0.90438191, 0.46061297, 0.60174

### Save the model

In [38]:
import pickle

In [39]:
# pickle the model file
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [40]:
# pickle the scaler file
with open('scaler','wb') as file:
    pickle.dump(scaler, file)